import scrapy
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor

import pandas as pd
import numpy as np
import os
import sqlite3
import xlsxwriter
import matplotlib.pyplot as plt
import seaborn as sns

# Arania para obtener los enlaces de todos los mangas


class AraniaMangadoorEnlaces(CrawlSpider):
    name = 'enlaces'  # Heredado (override)

    allowed_domains = [
        'gamesfull.org'
    ]

    start_urls = [
        'https://www.gamesfull.org/category/accion/page/1/',
        'https://www.gamesfull.org/category/accion/page/14/'
    ]

    # Busca todo
    regla_uno = (
        Rule(LinkExtractor(), callback='parse_page'),
    )

    url_segmento_permitido = (
        'accion/page/'
    )

    # Busca dentro de los dominios permitidos y los segmentos permitidos
    regla_dos = (
        Rule(
            LinkExtractor(
                allow_domains=allowed_domains,
                allow=url_segmento_permitido
            ), callback='parse_page'
        ),
    )

    rules = regla_dos  # Heredado (override)

    # Obtener títulos del manga
    def parse_page(self, response):
        lista_enlaces = response.css(
            'article.TPost.B > a::attr(href)').extract()
        for enlace in lista_enlaces:
            with open('../juegosEnlaces.txt', 'a+', encoding='utf-8') as archivo:  # se evita el try catch
                archivo.write('\'' + enlace + '\'' + ',\n')

# Arania para obtener toda la informacion de cada manga


class AraniaJuegos(scrapy.Spider):
    name = 'juegos'  # Heredado (override)

    urls = [
        'https://www.gamesfull.org/descargar-naruto-shippuden-ultimate-ninja-storm-revolution-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-naruto-shippuden-ultimate-ninja-storm-4-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-mages-of-mystralia-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-observer-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-naruto-shippuden-ultimate-ninja-storm-trilogy-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-binding-of-isaac-afterbirth-plus-espanol-mega-torrent-iso-hi2u/',
        'https://www.gamesfull.org/descargar-deadpool-espanol-mega-torrent-iso-flt/',
        'https://www.gamesfull.org/descargar-grand-theft-auto-v-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-devil-may-cry-4-special-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-devil-may-cry-3-special-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-battlefield-4-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/sniper-elite-3-dlc-espanol-mega-torrent-setup/',
        'https://www.gamesfull.org/mafia-ii-directors-cut-espanol-mega-torrent-iso-skidrow/',
        'https://www.gamesfull.org/crysis-3-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-injustice-2-legendary-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-fallout-new-vegas-ultimate-edition-espanol-torrent-googledrive/',
        'https://www.gamesfull.org/descargar-fallout-3-game-of-the-year-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-halo-2-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-alice-madness-returns-complete-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-brawlout-espanol-torrent-codex/',
        'https://www.gamesfull.org/descargar-typical-nightmare-espanol-torrent-plaza/',
        'https://www.gamesfull.org/descargar-tyler-model-005-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-q-u-b-e-2-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-state-of-mind-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-syndicate-gold-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/assassins-creed-unity-gold-edition/',
        'https://www.gamesfull.org/descargar-deaths-gambit-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-ball-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-company-of-heroes-2-master-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-total-war-rome-ii-emperor-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-chronicles-trilogy-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-rogue-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-liberation-hd-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-revelations-gold-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-brotherhood-complete-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-iv-black-flag-jackdaw-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-iii-complete-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-ii-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-directors-cut-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-mafia-iii-digital-deluxe-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-mafia-the-city-of-lost-heaven-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-escapists-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-arma-3-complete-campaign-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-vanquish-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-mega-man-x-legacy-collection-bundle-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-transformers-fall-of-cybertron-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-transformers-war-for-cybertron-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-total-war-saga-thrones-of-britannia-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-guts-and-glory-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-mothergunship-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-first-templar-special-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-prey-2017-mooncrash-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dark-souls-remastered-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-red-faction-guerrilla-re-mars-tered-espanol-mega-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-grip-combat-racing-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-lords-of-the-fallen-goty-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-bomber-crew-espanol-mega-torrent-iso-darksiders/',
        'https://www.gamesfull.org/descargar-helldivers-digital-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-shenmue-i-and-ii-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-earthfall-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-sinner-sacrifice-for-redemption-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-phantom-doctrine-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-men-of-war-assault-squad-2-complete-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-distance-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-formula-fusion-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-bendy-and-the-ink-machine-complete-edition-espanol-torrent-plaza/',
        'https://www.gamesfull.org/descargar-thenightfall-halloween-edition-espanol-torrent-plaza/',
        'https://www.gamesfull.org/descargar-the-evil-within-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-slime-rancher-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-my-hero-ones-justice-espanol-torrent-elamigo/',
        'https://www.gamesfull.org/descargar-party-hard-2-espanol-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-paw-patrol-on-a-roll-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-thronebreaker-the-witcher-tales-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-rise-of-the-tomb-raider-20-year-celebration-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-tomb-raider-game-of-the-year-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-tomb-raider-underworld-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-tomb-raider-anniversary-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-tomb-raider-legend-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-initial-ii-new-stage-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-origins-gold-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-9th-gate-espanol-torrent-plaza/',
        'https://www.gamesfull.org/descargar-valiant-hearts-the-great-war-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-magicka-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-absolver-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-call-of-duty-black-ops-iii-digital-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-captives-plot-of-the-demiurge-espanol-torrent-codex/',
        'https://www.gamesfull.org/descargar-mark-of-the-ninja-remastered-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-xcom-2-digital-deluxe-edition-espanol-mega-torrent-setup-repack/',
        'https://www.gamesfull.org/descargar-my-memory-of-us-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/fallout-4-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-final-fantasy-type-0-hd-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/lightning-returns-final-fantasy-xiii/',
        'https://www.gamesfull.org/descargar-final-fantasy-xiii-2-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-final-fantasy-xiii-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-epic-mickey-2-the-power-of-two-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-call-of-duty-ghosts-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-i-am-alive-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-wizard-of-legend-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-ni-no-kuni-ii-revenant-kingdom-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-rage-complete-edition-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-mirrors-edge-catalyst-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-ruse-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dmc-devil-may-cry-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-sonic-mania-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-diablo-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/devil-may-cry-hd-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-devil-may-cry-5-deluxe-edition-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-deus-ex-mankind-divided-digital-deluxe-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-deus-ex-human-revolution-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-eternity-the-last-unicorn-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dragon-ball-fighterz-ultimate-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-fighting-ex-layer-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-rad-rodgers-radical-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-darksiders-iii-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-thief-simulator-espanol-torrent-codex/',
        'https://www.gamesfull.org/descargar-far-cry-new-dawn-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-metro-exodus-gold-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-crackdown-3-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-yakuza-kiwami-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-far-cry-primal-apex-edition-espanol-mega-torrent-iso-cpy/',
        'https://www.gamesfull.org/descargar-ace-combat-7-skies-unknown-deluxe-edition-espanol-elamigos/',
        'https://www.gamesfull.org/descargar-overkills-the-walking-dead-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-god-eater-3-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-ghost-of-a-tale-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-metro-redux-bundle-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-re-legion-deluxe-edition-espanol-torrent-gog/',
        'https://www.gamesfull.org/descargar-the-hong-kong-massacre-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dungeon-siege-iii-collection-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-genesis-alpha-one-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-7-biohazard-espanol-mega-torrent-iso-cpy/',
        'https://www.gamesfull.org/descargar-valkyria-chronicles-4-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-northgard-english-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-endless-space-2-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-lego-the-incredibles-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-lost-via-domus-the-video-game-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-james-camerons-avatar-the-game-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-jurassic-park-the-game-espanol-mega-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-desperados-wanted-dead-or-alive-re-modernized-espanol-mega-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-last-remnant-espanol-mega-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dream-alone-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-darksiders-ii-deathinitive-edition-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-darksiders-warmastered-edition-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargarcrying-is-not-enough-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-halo-wars-2-complete-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-anima-gate-of-memories-the-nameless-chronicles-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-zombie-army-trilogy-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-super-bomberman-r-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-moonlighter-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-lara-croft-and-the-guardian-of-light-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-karters-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-spider-man-web-of-shadows-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dreamfall-chapters-complete-season-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-harry-potter-and-the-half-blood-prince-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-harry-potter-and-the-order-of-the-phoenix-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-harry-potter-and-the-prisoner-of-azkaban-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-harry-potter-and-the-deathly-hallows-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-spider-man-shattered-dimensions-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-spider-man-the-amazing-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-overload-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-downward-spiral-horus-station-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-zombie-forest-2-espanol-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/descargar-street-fighter-30th-anniversary-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-redout-enhanced-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-sacred-2-gold-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-runner3-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-alien-isolation-complete-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-ultimate-epic-battle-simulator-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-king-of-fighters-xiv-steam-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descarga-rattack-of-the-killer-furries-espanol-mega-torrent-iso-darksiders/',
        'https://www.gamesfull.org/descargar-battletech-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-state-of-decay-yose-day-one-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-medal-of-honor-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-medal-of-honor-airborne-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-medal-of-honor-pacific-assault-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-medal-of-honor-allied-assault-war-chest-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-portal-2-complete-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-snake-pass-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-despoiler-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-s-t-a-l-k-e-r-trilogy-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-bayonetta-digital-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-mirrors-edge-complete-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-sword-art-online-hollow-fragment-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dragon-ball-xenoverse-bundle-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-warhammer-vermintide-2-espanol-mega-torrent-portable-voksi/',
        'https://www.gamesfull.org/descargar-batman-the-enemy-within-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-the-legend-of-zelda-breath-of-the-wild-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-mass-effect-andromeda-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-beast-quest-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-gears-of-war-4-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-metal-gear-rising-revengeance-special-edition-espanol-mega-torrent-setup/',
        'https://www.gamesfull.org/metal-gear-solid-v-ground-zeroes-espanol-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/life-is-strange-episodio-5-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-far-cry-4-gold-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-far-cry-3-complete-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-life-is-strange-before-the-storm-deluxe-edition-espanol-mega-torrent-iso-elamigos-2/',
        'https://www.gamesfull.org/descargar-distortions-english-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-battlezone-combat-commander-english-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-guns-gore-and-cannoli-2-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-call-of-duty-4-modern-warfare-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-doom-espanol-mega-torrent-postable-voksi/',
        'https://www.gamesfull.org/descargar-titanfall-2-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-just-cause-3-xl-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dishonored-game-of-the-year-edition-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-the-witcher-3-wild-hunt-complete-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-the-walking-dead-complete-second-season-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-battlefield-1-ultimate-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-injustice-gods-among-us-ultimate-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-watch-dogs-complete-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-watch-dogs-2-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-hunt-down-the-freeman-english-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-past-cure-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-hitman-the-complete-first-season-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-marvel-vs-capcom-infinite-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-swords-of-ditto-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-payday-2-ultimate-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/city-of-brass/',
        'https://www.gamesfull.org/descargar-one-piece-pirate-warriors-3-gold-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-killer-instinct-espanol-mega-torrent-iso-elamigos-2/',
        'https://www.gamesfull.org/descargar-mad-max-ripper-special-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-minecraft-story-mode-season-2-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-call-to-arms-basic-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-starcraft-ii-the-complete-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-light-fall-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-bullet-witch-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-nier-automata-day-one-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-walking-dead-complete-first-season-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-tom-clancys-ghost-recon-wildlands-gold-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-remothered-tormented-fathers-hd-espanol-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/descargar-amberskull-espanol-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/descargar-lego-marvel-super-heroes-2-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-sword-art-online-fatal-bullet-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-masters-of-anima-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-extinction-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/fallout-shelter-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-kartong-death-by-cardboard-english-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-medal-of-honor-warfighter-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-unravel-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-raiders-of-the-broken-planet-espanol-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/descargar-dynasty-warriors-9-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-lord-of-the-rings-war-in-the-north-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-lord-of-the-rings-conquest-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-lord-of-the-rings-the-return-of-the-king-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-half-life-2-the-orange-box-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-castlevania-lords-of-shadow-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-castlevania-lords-of-shadow-mirror-of-fate-hd-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-castlevania-lords-of-shadow-ultimate-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-spellforce-2-anniversary-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-spellforce-platinum-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dying-light-the-following-enhanced-edition-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-final-fantasy-x-x-2-hd-remaster-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-victor-vran-overkill-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-shadows-awakening-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-planet-alpha-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-final-fantasy-viii-steam-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-final-fantasy-ix-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-hollow-knight-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-insomnia-the-ark-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-rocket-league-deluxe-edition-espanol-portable-ali213/',
        'https://www.gamesfull.org/descargar-vampyr-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-works-of-mercy-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-jurassic-world-evolution-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dragon-quest-xi-echoes-of-an-elusive-age-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-super-luckys-tale-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-rush-a-disney-pixar-adventure-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-star-control-origins-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-murderous-pursuits-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-dragon-quest-heroes-ii-explorers-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dragon-quest-heroes-slime-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-air-conflicts-collection-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-revelations-2-complete-season-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-revelations-complete-pack-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-operation-raccoon-city-complete-pack-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-6-complete-pack-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-recore-definitive-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-black-clover-quartet-knights-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-lego-worlds-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-5-gold-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-4-ultimate-hd-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-zero-hd-remaster-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-hd-remaster-biohazard-hd-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-tom-clancys-rainbow-six-siege-complete-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-elex-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-state-of-decay-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/middle-earth-shadow-of-war-gold-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-conan-exiles-barbarian-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dead-cells-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-guts-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dead-rising-3-apocalypse-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dead-rising-4-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-xenoblade-chronicles-x-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/dscargar-bayonetta-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-silent-descent-english-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/descargar-mass-effect-ultimate-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-mass-effect-2-ultimate-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-mass-effect-3-complete-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-homeworld-remastered-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-styx-master-of-shadows-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-limbo-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-origins-espanol-mega-torrent-iso-cpy/',
        'https://www.gamesfull.org/descargar-dead-space-espanol-mega-torrent-isos-elamigos/',
        'https://www.gamesfull.org/descargar-dead-space-2-espanol-mega-torrent-isos-elamigos/',
        'https://www.gamesfull.org/descargar-moto-racer-4-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dead-space-3-espanol-mega-torrent-isos-elamigos/',
        'https://www.gamesfull.org/descargar-syndicate-2012-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-alpha-protocol-the-espionage-rpg-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-agents-of-mayhem-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dragon-age-inquisition-deluxe-edition-espanol-mega-torrent-iso-cpy/',
        'https://www.gamesfull.org/descargar-tesla-vs-lovecraft-espanol-mega-torrent-iso-darksiders/',
        'https://www.gamesfull.org/descargar-star-ocean-the-last-hope-4k-and-full-hd-remaster-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-sonic-forces-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-homefront-ultimate-edition-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-saints-row-iv-game-of-the-century-edition-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-saints-row-the-third-the-full-package-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-saints-row-2-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-saints-row-gat-out-of-hell-espanol-mega-torrent-setup/',
        'https://www.gamesfull.org/descargar-road-redemption-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-sleeping-dogs-definitive-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-ace-combat-assault-horizon-enhanced-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-sonic-the-hedgehog-4-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-universe-at-war-earth-assault-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-xcom-enemy-unknown-the-complete-edition-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-the-bureau-xcom-declassified-complete-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-dead-or-alive-5-last-round-dlc-espanol-mega-torrent-portable-ali213/',
        'https://www.gamesfull.org/descargar-prey-espanol-mega-torrent-iso-elamigos-2/',
        'https://www.gamesfull.org/descargar-hidden-dragon-legend-english-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-darkwood-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-star-wars-the-force-unleashed-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-murdered-soul-suspect-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-unreal-tournament-3-black-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-senran-kagura-burst-renewal-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-desolate-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-lucius-iii-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-styx-shards-of-darkness-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-ark-survival-evolved-v232-4-english-mega-torrent-setup-repack/',
        'https://www.gamesfull.org/descargar-soulcalibur-vi-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-beyond-good-and-evil-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-onimusha-warlords-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-hellblade-senuas-sacrifice-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-strange-brigade-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-tales-of-vesperia-definitive-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dark-souls-iii-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dark-souls-ii-scholar-of-the-first-sin-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dark-souls-prepare-to-die-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-remember-me-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-republique-remastered-complete-season-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-hand-of-fate-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dishonored-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dishonored-death-of-the-outsider-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-forest-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-battlefield-v-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-ashen-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-yakuza-0-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dynasty-warriors-7-xtreme-legends-definitive-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-just-cause-4-gold-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-hello-neighbor-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-asterix-obelix-xxl-2-remastered-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-naruto-to-boruto-shinobi-striker-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-total-war-warhammerii-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/final-fantasy-xv-windows-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-far-cry-5-gold-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-wolfenstein-ii-the-new-colossus-digital-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-mega-man-11-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-underworld-ascendant-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-sunset-overdrive-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-warriors-orochi-4-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-a-way-out-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-odyssey-gold-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-kursk-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-warhammer-40000-dawn-of-war-ii-master-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/crysis-2-maximun-edition-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/crysis-maximum-edition-espanol-mega-torrent-isos-repack/',
        'https://www.gamesfull.org/descargar-bike-rush-espanol-mega-torrent-iso-hi2u/',
        'https://www.gamesfull.org/descargar-total-war-attila-special-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-napoleon-total-war-imperial-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-command-and-conquer-generals-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-command-and-conquer-red-alert-3-complete-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-command-and-conquer-3-tiberium-wars-complete-collection-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-ty-the-tasmanian-tiger-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-ty-the-tasmanian-tiger-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-way-of-redemption-espanol-mega-torrent-iso-postmortem/',
        'https://www.gamesfull.org/descargar-sword-art-online-hollow-realization-deluxe-edition-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-tyranny-overlord-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-middle-earth-shadow-of-mordor-goty-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-outcast-second-contact-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-bulletstorm-full-clip-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-nioh-complete-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-risen-trilogy-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-evil-within-complete-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-rise-of-nations-extended-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-soldiers-of-the-universe-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-rogue-trooper-redux-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/the-witcher-2-assassins-of-kings-enhanced-edition-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/the-witcher-enhanced-edition-directors-cut-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-sonic-lost-world-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-sonic-generations-dlc-espanol-mega-torrent-iso-prophet/',
        'https://www.gamesfull.org/descargar-hob-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-wolfenstein-the-old-blood-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-wolfenstein-the-new-order-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-wolfenstein-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-megaton-rainfall-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-ben-10-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-road-rage-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-call-of-duty-world-at-war-ii-digital-deluxe-espanol-mega-torrent-iso-elamigos-2/',
        'https://www.gamesfull.org/descargar-marvels-guardians-of-the-galaxy-telltale-complete-season-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-one-piece-unlimited-world-red-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-ruiner-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-f1-2017-special-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-accel-world-vs-sword-art-online-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-yakuza-0-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-runner3-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-evil-within-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-strange-brigade-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-q-u-b-e-2-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-the-walking-dead-complete-first-season-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-absolver-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-the-escapists-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-party-hard-2-espanol-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-raiders-of-the-broken-planet-espanol-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/comprar-the-division-2-online-2x1/',
        'https://www.gamesfull.org/comprar-red-dead-redemption-2/',
        'https://www.gamesfull.org/comprar-star-wars-battlefront-2/',
        'https://www.gamesfull.org/comprar-plants-vs-zombies-battle-for-neighborville/',
        'https://www.gamesfull.org/descargar-formula-fusion-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-karters-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-soldiers-of-the-universe-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-distortions-english-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-road-redemption-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-kartong-death-by-cardboard-english-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-mages-of-mystralia-espanol-mega-torrent-iso-reloaded/',
        'https://www.gamesfull.org/descargar-guts-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-silent-descent-english-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/descargar-way-of-redemption-espanol-mega-torrent-iso-postmortem/',
        'https://www.gamesfull.org/descargar-zombie-forest-2-espanol-mega-torrent-iso-plaza/',
        'https://www.gamesfull.org/comprar-red-dead-redemption-2/',
        'https://www.gamesfull.org/comprar-the-division-2-online-2x1/',
        'https://www.gamesfull.org/descargar-initial-ii-new-stage-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-gears-5-ultimate-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-daymare-1998-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-sea-of-solitude-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-walking-dead-the-telltale-definitive-series-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-quantum-break-steam-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-greedfall-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-spyro-reignited-trilogy-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-control-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-ancestors-the-humankind-odyssey-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-little-nightmares-deluxe-edition-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-portal-knights-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-rad-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-darq-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-warhammer-chaosbane-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-wolfenstein-youngblood-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-remnant-from-the-ashes-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-apsulov-end-of-gods-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-sniper-ghost-warrior-3-season-pass-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-blackout-club-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-we-happy-few-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-monster-boy-and-the-cursed-kingdom-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-immortal-unchained-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-one-piece-world-seeker-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dragon-ball-xenoverse-2-deluxe-edition-espanol-mega-torrent-portable-3dm/',
        'https://www.gamesfull.org/descargar-total-war-three-kingdoms-espanol-elamigos-torrent/',
        'https://www.gamesfull.org/descargar-attack-on-titan-2-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-metal-gear-solid-v-the-phantom-pain-espanol-mega-torrent-iso-cpy/',
        'https://www.gamesfull.org/descargar-shadow-of-the-tomb-raider-croft-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-star-wars-battlefront-ii-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-my-friend-pedro-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-bloodstained-ritual-of-the-night-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-steel-division-2-total-conflict-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-overcooked-2-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-f-e-a-r-2-project-origin-complete-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-borderlands-the-handsome-collection-remastered-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-steel-rats-espanol-torrent-codex/',
        'https://www.gamesfull.org/descargar-american-fugitive-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-hearts-of-iron-iv-field-marshal-edition-espanol-mega-torrent-portable-3dm/',
        'https://www.gamesfull.org/descargar-world-war-z-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-trover-saves-the-universe-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-jump-force-ultimate-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-daemon-x-machina-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-street-fighter-v-arcade-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-dead-or-alive-6-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-pine-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-dragon-ball-z-kakarot-ultimate-edition-espanol-elamigos/',
        'https://www.gamesfull.org/descargar-journey-to-the-savage-planet-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-terminator-resistance-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/comprar-red-dead-redemption-2/',
        'https://www.gamesfull.org/descargar-sekiro-shadows-die-twice-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-resident-evil-2-2019-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-outer-wilds-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-age-of-mythology-extended-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-pixark-espanol-mega-torrent-portable/',
        'https://www.gamesfull.org/descargar-halo-the-master-chief-collection-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-darksiders-genesis-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-phoenix-point-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/comprar-plants-vs-zombies-battle-for-neighborville/',
        'https://www.gamesfull.org/descargar-heavy-rain-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-star-wars-jedi-fallen-order-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/comprar-the-division-2-online-2x1/',
        'https://www.gamesfull.org/descargar-rune-ii-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-subnautica-espanol-mega-torrent-iso-codex/',
        'https://www.gamesfull.org/descargar-borderlands-3-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-outer-worlds-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-deliver-us-the-moon-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-monkey-king-hero-is-back-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/batman-arkham-knight-dlc-espanol-mega-torrent-iso-cpy/',
        'https://www.gamesfull.org/descargar-john-wick-hex-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-trine-4-the-nightmare-prince-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-hitman-2-gold-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-ghostbusters-the-video-game-remastered-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-wild-eight-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-contra-rogue-corps-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-code-vein-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-rage-2-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-surge-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-surge-2-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-ni-no-kuni-wrath-of-the-white-witch-remastered-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-sniper-elite-v2-remastered-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-kingdom-come-deliverance-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-a-plague-tale-innocence-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-observation-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-assassins-creed-iii-remastered-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-yakuza-kiwami-2-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-close-to-the-sun-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-planet-nomads-espanol-mega-torrent-setup-gog/',
        'https://www.gamesfull.org/descargar-fade-to-silence-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-mordhau-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-bioshock-infinite-game-of-the-year-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-cuphead-deluxe-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-south-park-the-fractured-but-whole-gold-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-mega-man-legacy-collection-bundle-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-bioshock-remastered-collection-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-lego-dc-super-villains-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/comprar-star-wars-battlefront-2/',
        'https://www.gamesfull.org/descargar-batman-the-telltale-series-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-batman-arkham-origins-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-superhot-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-batman-arkham-origins-blackgate-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-batman-arkham-city-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-batman-arkham-asylum-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-supraland-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-grim-dawn-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-the-walking-dead-a-new-frontier-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-sniper-elite-4-deluxe-edition-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-walking-dead-survival-instinct-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-walking-dead-michonne-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-lego-marvels-avengers-torrent-elamigos/',
        'https://www.gamesfull.org/tekken-7-deluxe-edition/',
        'https://www.gamesfull.org/descargar-killing-floor-2-digital-deluxe-edition-espanol-mega-torrent-portable-3dm/',
        'https://www.gamesfull.org/descargar-xenon-racer-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-the-walking-dead-the-final-season-espanol-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-lego-jurassic-world-torrent-elamigos/',
        'https://www.gamesfull.org/descargar-enderal-forgotten-stories-espanol-torrent-elamigos/'
    ]

    urls_prueba = [
        'https://www.gamesfull.org/descargar-the-legend-of-zelda-breath-of-the-wild-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-mass-effect-3-complete-edition-espanol-mega-torrent-iso-elamigos/',
        'https://www.gamesfull.org/descargar-tomb-raider-legend-espanol-torrent-elamigos/'
    ]

    titulo_juegos = []
    fechas_juegos = []
    uploader_juegos = []
    tamanio_juegos = []
    visitas_juegos = []
    votos_juegos = []
    rating_juegos = []

    def start_requests(self):
        for url in self.urls:
            yield scrapy.Request(url=url)

    def parse(self, response):
        titulos = response.css('header.Top > h1.Title::text').get()
        self.titulo_juegos.append(titulos)

        fechas = response.css(
            'header.Top > div.Info > span.Date::text').get()
        self.fechas_juegos.append(fechas)

        uploader = response.css(
            'header.Top > div.Info > span.Qlty::text').get()
        self.uploader_juegos.append(uploader)

        tamanio = response.css(
            'header.Top > div.Info > span.Time::text').get()
        self.tamanio_juegos.append(tamanio)

        visitas = response.css(
            'header.Top > div.Info > span.Views::text').get()

        calificaciones = response.css(
            'div.post-ratings > strong::text').extract()
        calificaciones[1] = calificaciones[1].replace(',','.')

        self.votos_juegos.append(calificaciones[0])
        self.rating_juegos.append(calificaciones[1])

        visitas = visitas.replace(' visitas', '')
        visitas = visitas.replace('.','')
        self.visitas_juegos.append(visitas)

        lista_titulos = pd.Series(self.titulo_juegos)
        lista_fechas = pd.Series(self.fechas_juegos)
        lista_uploader = pd.Series(self.uploader_juegos)
        lista_tamanio = pd.Series(self.tamanio_juegos)
        lista_visitas = pd.Series(self.visitas_juegos)
        lista_votos = pd.Series(self.votos_juegos)
        lista_ratings = pd.Series(self.rating_juegos)
        
        path_guardado = 'C://Users//MORALES//Documents//GitHub//py-morales-banda-juan-jose//Deberes//Proyecto2//Gamesfull//Juegos.xlsx'

        df = pd.DataFrame({'Titulo': lista_titulos,
                           'Votos': lista_votos,
                           'Rating': lista_ratings,
                           'Fechas': lista_fechas,
                           'Uploader': lista_uploader,
                           'Tamanio': lista_tamanio,
                           'Visitas': lista_visitas})

        df.to_excel(path_guardado, sheet_name='Gamesfull', index=False)
